feat: Controllers, Services and Repository for Item and User
SergeyMont/java-shareit pull request #1
Opened 2022-07-11 12:36 UTC by SergeyMont

2022-07-14 20:53 UTC, kukolev requested changes

2022-07-14 20:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
>  /**
Здесь в todo не хватает информации о том, что класс будет реализован в следующих спринтах.

2022-07-14 20:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>  /**
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-07-14 20:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>  /**
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-07-14 20:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    Long id;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-07-14 20:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    Long id;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-07-14 20:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/requests/ItemRequest.java
> +    Long id;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-07-14 20:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/requests/ItemRequest.java
>  /**
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-07-14 20:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/User.java
>  /**
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-07-14 20:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/User.java
> +    Long id;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-07-14 20:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/UserController.java
>  /**
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-07-14 20:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private void emailValidation(UserDto userDto) {
Нарушение кодстайла: Название метода лучше начинать с глагола, обозначающего действие над аргументами или над классом, которому принадлежит метод. Так назначение метода будет понятно сразу из названия. Нужно поправить.

2022-07-14 20:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    Long id;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-07-14 20:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +    private Long counter = Long.valueOf(0);
Использование .valueof для задания нуля это слишком сложно. Можно просто `private Long counter = 0L`

2022-07-14 20:53 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +            User u = map.get(user.getId());
Нарушение кодстайла: Переменные должны называться так, чтобы из названия можно было понять, за что отвечает переменная. Так код будет понятней при анализе.

2022-07-15 13:27 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
>  /**
fix

2022-07-15 13:28 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>  /**
fix

2022-07-15 13:28 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>  /**
fix

2022-07-15 13:29 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    Long id;
fix

2022-07-15 13:30 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    Long id;
fix

2022-07-15 13:32 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/requests/ItemRequest.java
> +    Long id;
fix

2022-07-15 13:33 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/requests/ItemRequest.java
>  /**
fix

2022-07-15 13:34 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/user/User.java
>  /**
fix

2022-07-15 13:34 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/user/User.java
> +    Long id;
fix

2022-07-15 13:35 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/user/UserController.java
>  /**
fix

2022-07-15 13:36 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private void emailValidation(UserDto userDto) {
fix

2022-07-15 13:36 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    Long id;
fix

2022-07-15 13:37 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +    private Long counter = Long.valueOf(0);
fix

2022-07-15 13:39 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +            User u = map.get(user.getId());
fix

2022-07-15 16:16 UTC, kukolev requested changes

2022-07-15 16:16 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private void validationUserEmail(UserDto userDto) {
Метод все еще назван некорректно. Validation это не глагол. Нужно сделать в соответствии с кодстайлом.

2022-07-18 18:46 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private void validationUserEmail(UserDto userDto) {
fix

2022-07-19 07:40 UTC, kukolev approved these changes

2022-07-21 07:59 UTC, merged