feat: add Booking, Comment, API Repositories, Controllers.
SergeyMont/java-shareit pull request #2
Opened 2022-07-31 16:15 UTC by SergeyMont

2022-08-01 07:52 UTC, kukolev requested changes

2022-08-01 07:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (!(Objects.equals(booking.getBooker().getId(), userId) || Objects.equals(booking.getItem().getOwner(), userId))) {
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-08-01 07:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        Item item = ItemMapper.toItem(itemService.getItemById(bookingDto.getItemId()));
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-08-01 07:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        Booking booking = bookingService.getBooking(bookingId);
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-08-01 07:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (!ObjectUtils.containsConstant(State.values(), state)) {
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-08-01 07:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (!ObjectUtils.containsConstant(State.values(), state)) {
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-08-01 07:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/dto/ExternalBookingDto.java
> +    LocalDateTime start;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-08-01 07:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        ItemCommentDto result = ItemMapper.itemCommentDto(itemService.getItemById(itemId));
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-08-01 07:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.getAllByUserId(userId).stream()
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-08-01 07:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (text.isEmpty()) {
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-08-01 07:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (!bookingService.isHasBookingsByItemIdAndUserId(id, userId)) {
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-08-01 07:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +            ItemDto i = getItemById(itemDto.getId());
Нарушение кодстайла: Переменные должны называться так, чтобы из названия можно было понять, за что отвечает переменная. Так код будет понятней при анализе.

Также нужно поправить ниже

2022-08-02 18:50 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/booking/dto/ExternalBookingDto.java
> +    LocalDateTime start;
fix

2022-08-02 18:52 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (!(Objects.equals(booking.getBooker().getId(), userId) || Objects.equals(booking.getItem().getOwner(), userId))) {
fix

2022-08-02 18:52 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        Item item = ItemMapper.toItem(itemService.getItemById(bookingDto.getItemId()));
fix

2022-08-02 18:52 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        Booking booking = bookingService.getBooking(bookingId);
fix

2022-08-02 18:52 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (!ObjectUtils.containsConstant(State.values(), state)) {
fix

2022-08-02 18:52 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (!ObjectUtils.containsConstant(State.values(), state)) {
fix

2022-08-02 19:18 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +            ItemDto i = getItemById(itemDto.getId());
fix

2022-08-02 19:19 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (!bookingService.isHasBookingsByItemIdAndUserId(id, userId)) {
fix

2022-08-02 19:19 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (text.isEmpty()) {
fix

2022-08-02 19:45 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.getAllByUserId(userId).stream()
fix

2022-08-02 19:45 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        ItemCommentDto result = ItemMapper.itemCommentDto(itemService.getItemById(itemId));
fix

2022-08-03 16:35 UTC, kukolev requested changes

2022-08-03 16:35 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        validationManager.validateBookingOwnerBooker(id, userId);
Валидация это тоже часть бизнес-логики и ей место в сервисе. Нужно поправить здесь и ниже.

2022-08-07 05:50 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        validationManager.validateBookingOwnerBooker(id, userId);
fix

2022-08-07 08:56 UTC, kukolev approved these changes

2022-08-08 17:43 UTC, merged