feat: Item Requests and Tests
SergeyMont/java-shareit pull request #3
Opened 2022-08-15 20:06 UTC by SergeyMont

2022-08-17 06:27 UTC, kukolev requested changes

2022-08-17 06:27 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +        return Objects.equals(id, booking.id) && Objects.equals(item, booking.item) && Objects.equals(booker, booking.booker) && status == booking.status;
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-17 06:27 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/dto/ShortBookingDto.java
> +        return Objects.equals(id, that.id) && Objects.equals(itemId, that.itemId) && Objects.equals(bookerId, that.bookerId) && status == that.status;
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-17 06:27 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>      public ItemCommentDto findItemById(@PathVariable("itemId") Long itemId, @RequestHeader("X-Sharer-User-Id") Long userId) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-17 06:27 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        Pageable pageable = PageRequest.of(from, size);
Это часть логики, место которой в сервисе. Нужно перенести логику в сервис.

Аналогично нужно поправить в остальных методах.

2022-08-17 06:27 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +                    itemCommentDto.setComments(commentRepository.findAllByItemId(itemDto.getId()).stream().map(CommentMapper::toCommentDto).collect(Collectors.toList()));
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-17 06:27 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        return itemRepository.findAllByNameContainingIgnoreCaseOrDescriptionContainingIgnoreCaseAndAvailableTrue(text, text, pageable)
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-17 06:27 UTC, kukolev commented on src/main/java/ru/practicum/shareit/requests/ItemRequest.java
> +    @Size(max = 4000)
ТЗ не подразумевает ограничение в 4000 символов на размер поля. Нужно убрать ограничение.

2022-08-17 06:27 UTC, kukolev commented on src/main/java/ru/practicum/shareit/requests/ItemRequestController.java
> +    public ItemRequestDto createNewRequest(@Valid @RequestHeader("X-Sharer-User-Id") Long userId, @RequestBody ExternalRequestDto requestDto) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-17 06:27 UTC, kukolev commented on src/main/java/ru/practicum/shareit/requests/ItemRequestService.java
> +        return itemRequestRepository.findAll(pageable).stream().map(RequestMapper::toItemRequestDto).collect(Collectors.toList());
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-17 06:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    Booking booking = new Booking(1L, LocalDateTime.now(), LocalDateTime.now().plusHours(2L), item, user2, Status.WAITING);
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-17 06:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +    User user = new User(1L, "Simple User", "user@mail.ru");
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-08-17 06:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +        assertEquals(bookingRepository.findById(booking1.getId()).orElse(null), booking1);
Аргументы в assertEquals перепутаны. Первый аргумент должен быть booking1, т.к. первый аргумент это ожидаемое значение, а второй аргумент это фактическое.

Аналогично нужно поправить ниже.

2022-08-17 06:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    MockMvc mvc;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-08-17 06:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemServiceTest.java
> +    User user = new User(1L, "Simple User", "user@mail.ru");
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-08-17 06:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/requests/ItemRequestControllerTest.java
> +    MockMvc mvc;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-08-17 06:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/requests/ItemRequestControllerTest.java
> +        when(itemRequestService.getAllByUserId(anyLong())).thenReturn(List.of(RequestMapper.toItemRequestDto(itemRequest)));
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-17 06:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/requests/ItemRequestControllerTest.java
> +        when(itemRequestService.getAllRequestOrderByCreated(anyLong(), any())).thenReturn(List.of(RequestMapper.toItemRequestDto(itemRequest)));
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-17 06:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/requests/ItemRequestControllerTest.java
> +        when(itemRequestService.getRequestById(anyLong(), anyLong())).thenReturn(RequestMapper.toItemRequestDto(itemRequest));
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-17 06:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/requests/ItemRequestServiceTest.java
> +        ItemRequestDto itemRequest1 = itemRequestService.addNewRequest(itemRequest.getRequester().getId(), externalRequestDto);
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-17 06:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/requests/ItemRequestServiceTest.java
> +        assertEquals(itemRequestService.getAllByUserId(Long.valueOf(1)), List.of(RequestMapper.toItemRequestDto(itemRequest)));
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-17 06:27 UTC, kukolev commented on src/test/java/ru/practicum/shareit/requests/ItemRequestServiceTest.java
> +        assertEquals(itemRequestService.getRequestById(itemRequest.getId(), user.getId()), RequestMapper.toItemRequestDto(itemRequest));
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-17 11:35 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +        return Objects.equals(id, booking.id) && Objects.equals(item, booking.item) && Objects.equals(booker, booking.booker) && status == booking.status;
fix

2022-08-17 11:40 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/booking/dto/ShortBookingDto.java
> +        return Objects.equals(id, that.id) && Objects.equals(itemId, that.itemId) && Objects.equals(bookerId, that.bookerId) && status == that.status;
fix

2022-08-17 11:42 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>      public ItemCommentDto findItemById(@PathVariable("itemId") Long itemId, @RequestHeader("X-Sharer-User-Id") Long userId) {
fix

2022-08-17 11:50 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        Pageable pageable = PageRequest.of(from, size);
fix

2022-08-17 11:51 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +                    itemCommentDto.setComments(commentRepository.findAllByItemId(itemDto.getId()).stream().map(CommentMapper::toCommentDto).collect(Collectors.toList()));
fix

2022-08-17 11:56 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/requests/ItemRequest.java
> +    @Size(max = 4000)
Это ограничение есть в БД, перенес сюда ,чтобы на этапе валидации отсекать данные.

2022-08-17 11:57 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/requests/ItemRequestController.java
> +    public ItemRequestDto createNewRequest(@Valid @RequestHeader("X-Sharer-User-Id") Long userId, @RequestBody ExternalRequestDto requestDto) {
fix

2022-08-17 11:59 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/requests/ItemRequestService.java
> +        return itemRequestRepository.findAll(pageable).stream().map(RequestMapper::toItemRequestDto).collect(Collectors.toList());
fix

2022-08-17 12:08 UTC, SergeyMont commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    Booking booking = new Booking(1L, LocalDateTime.now(), LocalDateTime.now().plusHours(2L), item, user2, Status.WAITING);
fix

2022-08-17 12:21 UTC, SergeyMont commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +    User user = new User(1L, "Simple User", "user@mail.ru");
fix

2022-08-17 12:24 UTC, SergeyMont commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +        assertEquals(bookingRepository.findById(booking1.getId()).orElse(null), booking1);
fix

2022-08-17 12:33 UTC, SergeyMont commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    MockMvc mvc;
fix

2022-08-17 12:33 UTC, SergeyMont commented on src/test/java/ru/practicum/shareit/item/ItemServiceTest.java
> +    User user = new User(1L, "Simple User", "user@mail.ru");
fix

2022-08-17 12:34 UTC, SergeyMont commented on src/test/java/ru/practicum/shareit/requests/ItemRequestControllerTest.java
> +    MockMvc mvc;
fix

2022-08-17 12:34 UTC, SergeyMont commented on src/test/java/ru/practicum/shareit/requests/ItemRequestControllerTest.java
> +        when(itemRequestService.getAllByUserId(anyLong())).thenReturn(List.of(RequestMapper.toItemRequestDto(itemRequest)));
fix

2022-08-17 12:34 UTC, SergeyMont commented on src/test/java/ru/practicum/shareit/requests/ItemRequestControllerTest.java
> +        when(itemRequestService.getAllRequestOrderByCreated(anyLong(), any())).thenReturn(List.of(RequestMapper.toItemRequestDto(itemRequest)));
fix

2022-08-17 12:34 UTC, SergeyMont commented on src/test/java/ru/practicum/shareit/requests/ItemRequestControllerTest.java
> +        when(itemRequestService.getRequestById(anyLong(), anyLong())).thenReturn(RequestMapper.toItemRequestDto(itemRequest));
fix

2022-08-17 12:34 UTC, SergeyMont commented on src/test/java/ru/practicum/shareit/requests/ItemRequestServiceTest.java
> +        ItemRequestDto itemRequest1 = itemRequestService.addNewRequest(itemRequest.getRequester().getId(), externalRequestDto);
fix

2022-08-17 12:34 UTC, SergeyMont commented on src/test/java/ru/practicum/shareit/requests/ItemRequestServiceTest.java
> +        assertEquals(itemRequestService.getAllByUserId(Long.valueOf(1)), List.of(RequestMapper.toItemRequestDto(itemRequest)));
fix

2022-08-17 12:34 UTC, SergeyMont commented on src/test/java/ru/practicum/shareit/requests/ItemRequestServiceTest.java
> +        assertEquals(itemRequestService.getRequestById(itemRequest.getId(), user.getId()), RequestMapper.toItemRequestDto(itemRequest));
fix

2022-08-17 18:45 UTC, SergeyMont commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        return itemRepository.findAllByNameContainingIgnoreCaseOrDescriptionContainingIgnoreCaseAndAvailableTrue(text, text, pageable)
fix

2022-08-18 16:11 UTC, kukolev approved these changes

2022-08-31 05:56 UTC, merged