add: microservice architecture gateway and server
SergeyMont/java-shareit pull request #4
Opened 2022-09-02 20:37 UTC by SergeyMont

2022-09-03 08:18 UTC, kukolev requested changes

2022-09-03 08:18 UTC, kukolev commented on gateway/src/main/java/ru/practicum/gateway/booking/BookingController.java
> +        validateState(stateParam);
Валидация параметров это часть бизнес-логики приложения. Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-09-03 08:18 UTC, kukolev commented on gateway/src/main/java/ru/practicum/gateway/client/BaseClient.java
> +    private <T> ResponseEntity<Object> makeAndSendRequest(HttpMethod method, String path, Long userId, @Nullable Map<String, Object> parameters, @Nullable T body) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-09-03 08:18 UTC, kukolev commented on gateway/src/main/resources/application.properties
> +#logging.level.org.apache.http=DEBUG
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-09-04 06:15 UTC, SergeyMont commented on gateway/src/main/resources/application.properties
> +#logging.level.org.apache.http=DEBUG
fix

2022-09-04 06:18 UTC, SergeyMont commented on gateway/src/main/java/ru/practicum/gateway/client/BaseClient.java
> +    private <T> ResponseEntity<Object> makeAndSendRequest(HttpMethod method, String path, Long userId, @Nullable Map<String, Object> parameters, @Nullable T body) {
fix

2022-09-04 09:36 UTC, kukolev requested changes
Не выполнено требование ТЗ: Вынести в shareIt-gateway всю логику валидации входных данных — кроме той, которая требует работы с БД. Необходимо вынести валидацию входных данных в shareIt-gateway.

2022-09-04 09:36 UTC, kukolev commented on pom.xml
> +    <packaging>pom</packaging>
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-09-04 11:32 UTC, SergeyMont commented on gateway/src/main/java/ru/practicum/gateway/booking/BookingController.java
> +        validateState(stateParam);
fix

2022-09-04 11:34 UTC, SergeyMont commented on pom.xml
> +    <packaging>pom</packaging>
fix

2022-09-04 16:49 UTC, kukolev approved these changes

2022-09-07 21:05 UTC, merged